### ISSUE TITLE
打成jar包后访问http://localhost:8020/imagecenter/filelist，报错Error resolving template "/filelist"

### ISSUE THREAD

**Issue by yankj12** [yankj12/image-center#8]
打成jar包后访问`http://localhost:8020/imagecenter/filelist`，报如下错误：

```

org.thymeleaf.exceptions.TemplateInputException: Error resolving template "/filelist", template might not exist or might not be accessible by any of the configured Template Resolvers
	at org.thymeleaf.TemplateRepository.getTemplate(TemplateRepository.java:246) ~[thymeleaf-2.1.6.RELEASE.jar!/:2.1.6.RELEASE]
	at org.thymeleaf.TemplateEngine.process(TemplateEngine.java:1104) ~[thymeleaf-2.1.6.RELEASE.jar!/:2.1.6.RELEASE]
	at org.thymeleaf.TemplateEngine.process(TemplateEngine.java:1060) ~[thymeleaf-2.1.6.RELEASE.jar!/:2.1.6.RELEASE]
	at org.thymeleaf.TemplateEngine.process(TemplateEngine.java:1011) ~[thymeleaf-2.1.6.RELEASE.jar!/:2.1.6.RELEASE]
	at org.thymeleaf.spring4.view.ThymeleafView.renderFragment(ThymeleafView.java:335) ~[thymeleaf-spring4-2.1.6.RELEASE.jar!/:2.1.6.RELEASE]
```

**Comment by yankj12** [comment]
controller中返回视图，视图名称不能以`/`开头，比如你要找到filelist.html，那么return的视图名称为`filelist`而不是`/filelist`

参考[Error_template might not exist or might not be accessible by any of the configured Template Resolver](https://blog.csdn.net/jdzw_xcy/article/details/82388079)
